"""Developer onboarding guide and automated script generator (setup.sh / setup.ps1)."""

from pathlib import Path
from runrepo.analyzer import RepositoryAnalyzer
from runrepo.models import ProjectInfo
from runrepo.reproduce.models import ShareSpec


class ShareGenerator:
    """Generates human-readable onboarding documentation and automated cross-platform scripts."""

    def __init__(self, analyzer: RepositoryAnalyzer | None = None) -> None:
        self.analyzer = analyzer or RepositoryAnalyzer()

    def generate(self, repo_path: Path) -> ShareSpec:
        """Create a complete onboarding specification for a repository."""
        project_info = self.analyzer.analyze(repo_path)
        name = project_info.name or "project"

        runtimes = [f"{rt.name} {rt.version or ''}".strip() for rt in project_info.runtimes] or ["Node.js 22"]
        pms = [pm.name for pm in project_info.package_managers] or ["npm"]
        primary_pm = pms[0]
        services = [s.name for s in project_info.services] + [db.name for db in project_info.databases]
        env_vars = [ev.name for ev in project_info.environment_variables]
        scripts = {s.name: s.command for s in project_info.scripts}
        start_cmd = scripts.get("dev") or scripts.get("start") or f"{primary_pm} start"
        install_cmd = f"{primary_pm} install" if primary_pm != "uv" else "uv sync"

        # 1. Markdown Onboarding Guide
        md_lines = [
            f"# Developer Onboarding Guide for {name}",
            "",
            "## 1. Prerequisites",
            f"- **Runtimes:** {', '.join(runtimes)}",
            f"- **Package Manager:** `{primary_pm}`",
        ]
        if services:
            md_lines.append(f"- **Required Services:** {', '.join(services)} (Docker recommended)")

        md_lines.extend([
            "",
            "## 2. Environment Configuration",
            "Ensure a `.env` file is created with local development values:",
        ])
        if env_vars:
            md_lines.append("```bash")
            for ev in env_vars:
                md_lines.append(f"{ev}=...")
            md_lines.append("```")
        else:
            md_lines.append("No special environment variables required.")

        md_lines.extend([
            "",
            "## 3. Quick Start Commands",
            "```bash",
            f"# 1. Install dependencies",
            f"{install_cmd}",
            "",
            f"# 2. Start development application",
            f"{start_cmd}",
            "```",
            "",
            "Alternatively, run `runrepo .` for automated zero-touch setup and service provisioning.",
        ])
        markdown_guide = "\n".join(md_lines)

        # 2. Defensive Bash Script (setup.sh) - conforming to bash-pro
        bash_script = f"""#!/usr/bin/env bash
# ==============================================================================
# Automated Setup Script for {name}
# Generated by RunRepo
# ==============================================================================
set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${{BASH_SOURCE[0]}}")" && pwd -P)"
cd -- "$SCRIPT_DIR"

printf "[INFO] Setting up %s...\\n" "{name}"

# 1. Environment file setup
if [[ ! -f ".env" && -f ".env.example" ]]; then
    printf "[INFO] Creating .env from .env.example...\\n"
    cp -- ".env.example" ".env"
fi

# 2. Dependency installation
printf "[INFO] Installing dependencies using %s...\\n" "{install_cmd}"
{install_cmd}

printf "[OK] Setup completed successfully.\\n"
printf "[INFO] Run '%s' to start the application.\\n" "{start_cmd}"
"""

        # 3. Strict Windows PowerShell Script (setup.ps1) - conforming to powershell-windows
        ps_script = f"""# Strict PowerShell setup script for {name}
# Generated by RunRepo
Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $ScriptDir

Write-Output "[INFO] Setting up {name} on Windows..."

# 1. Environment file setup
if ((-not (Test-Path ".env")) -and (Test-Path ".env.example")) {{
    Write-Output "[INFO] Creating .env from .env.example..."
    Copy-Item ".env.example" ".env"
}}

# 2. Dependency installation
Write-Output "[INFO] Installing dependencies using {install_cmd}..."
& {install_cmd}

Write-Output "[OK] Setup completed successfully."
Write-Output "[INFO] Run '{start_cmd}' to start the application."
"""

        return ShareSpec(
            project_name=name,
            target_path=str(repo_path),
            markdown_guide=markdown_guide,
            bash_script=bash_script,
            powershell_script=ps_script,
            required_env_vars=env_vars,
            required_ports=[],
        )
